[package]
name = "ego_ops_mod"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/mod.rs"

[dependencies]
candid = "0.8.4"
ic-cdk = "0.6.8"
ic-cdk-macros = "0.6.8"
ic-certified-map = "0.3.0"
serde = "1.0.136"
async-trait = "0.1.57"
md5 = "0.7.0"
ego_types = { path = "../../../lib/ego_types"}
ego_dev_mod = {path = "../../ego_dev/mod"}
ego_store_mod = {path = "../../ego_store/mod"}
ego_tenant_mod = {path = "../../ego_tenant/mod"}

[dev-dependencies]
mockall = "0.11.2"
tokio = {version="1.21.0", features=["full"]}