[package]
name = "ego_ops_mod"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/mod.rs"

[dependencies]
ic-cdk = "0.5.0"
ic-cdk-macros = "0.5.0"
ic-types = "0.4.0"
ic-certified-map = "0.3.0"
candid = "0.7.14"
serde = "1.0.136"
async-trait = "0.1.57"
md5 = "0.7.0"
ego_types = { path = "../../../lib/ego_types"}
ego_utils = { path = "../../../lib/ego_utils" }
