[package]
name = "ego_tenant"
version = "0.1.0"
edition = "2021"


[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[[bin]]
name = "ego-tenant"
path = "src/main.rs"


[dependencies]
ic-cdk = "0.5.0"
ic-cdk-macros = "0.5.0"
ic-types = "0.4.0"
log = "0.4"
anyhow = "1.0.51"
thiserror = "1.0"
candid = "0.7.12"
serde = "1.0.116"
serde_json = "1.0"
ic-kit = "0.4.3"
serde_bytes = "0.11"
serde_cbor = "0.11"
serde_with = "1.6.2"
ego_tenant_mod = { path = "../mod" }
ego_users = { path = "../../../lib/ego_users"}
ego_types = { path = "../../../lib/ego_types"}
ego_macros = { path = "../../../lib/ego_macros" }