[package]
name = "ego_tenant"
version = "0.1.0"
edition = "2021"


[lib]
path = "src/actor.rs"
crate-type = ["cdylib"]

[[bin]]
name = "ego-tenant"
path = "src/main.rs"


[dependencies]
candid = "0.8.4"
ic-cdk = { version = "0.6.8", features = ["timers"] }
ic-cdk-macros = "0.6.8"
log = "0.4"
anyhow = "1.0.51"
thiserror = "1.0"
serde = "1.0.116"
serde_json = "1.0"
serde_bytes = "0.11"
serde_cbor = "0.11"
serde_with = "2.1.0"
ego_tenant_mod = { path = "../mod" }
ego_types = { path = "../../../lib/ego_types" }
ego_macros = { path = "../../../lib/ego_macros" }
ego_lib = { path = "../../../lib/ego_lib" }
ego_inner_rpc = { path ="../../../lib/ego_inner_rpc" }