// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

interface IAccessContext {
  canAdmin: boolean;
  canAudit: boolean;
  canDeveloper: boolean;
}
export const AccessContext = React.createContext<IAccessContext>(null);
