[workspace]
members = [
    "infra/ego_tenant/actor",
    "infra/ego_tenant/mod",
    "infra/ego_dev/actor",
    "infra/ego_dev/mod",
    "lib/ego_utils",
    "lib/ego_roles",
]

[profile.release]
lto = true
opt-level = 'z'