// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import { Result, Button } from 'antd';
import { IRoute } from '@/routes/renderRoutes/renderRoutes';
import { useHistory } from 'react-router-dom';

const Exception: React.FC<{
  children: React.ReactNode;
  route?: IRoute;
  notFound?: React.ReactNode;
  noAccessible?: React.ReactNode;
}> = (props) => {
  const history = useHistory()
  return (
    // render custom 404
    (!props.route && props.notFound) ||
    // render custom 403
    (props.route?.unaccessible && props.noAccessible) ||
    // render default exception
    ((!props.route || props.route.unaccessible) && (
      <Result
        status={props.route ? '403' : '404'}
        title={props.route ? '403' : '404'}
        subTitle={props.route ? '抱歉，你无权访问该页面' : '抱歉，你访问的页面不存在'}
        extra={
          <Button type="primary" onClick={() => history.push('/')}>
            返回首页
          </Button>
        }
      />
    )) ||
    // normal render
    props.children
  )
};

export default Exception;
