name: Rust

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: setup env
        run: |
          sudo apt install gcc-multilib
          rustup target add wasm32-unknown-unknown
      - name: install dfx and install nns
        run: |
          sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
      - name: Get DIDc
        run: |
          curl -L https://github.com/dfinity/candid/releases/download/2022-08-09/didc-linux64 -o /usr/local/bin/didc && chmod +x /usr/local/bin/didc
          export PATH=/usr/local/bin:$PATH
      - name: Generate credentials
        run: |
          curl -L https://github.com/dfinity/quill/releases/download/v0.2.15/quill-linux-x86_64 -o ./quill && chmod +x ./quill
          ./quill generate --seed-file credentials/seedPhrase.txt --pem-file credentials/production.pem
          dfx identity new me --disable-encryption
          dfx identity use me
      - name: copy network settings
        run: |
          cp ./default_network.json ~/.config/dfx/networks.json
      - name: run dfx
        run: dfx start --clean --background
      - name: pnpm
        run: npm install -g pnpm && pnpm install
      - name: Build
        run: pnpm run ego:run
      - name: Run tests
        run: pnpm run test
